CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Only skilled TRAINERS can collect\n"
    .string "POKéMON BADGES.\p"
    .string "I see you have at least one.\p"
    .string "Those BADGES have amazing secrets,\n"
    .string "did you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Now then…\p"
    .string "Which of the eight BADGES should\n"
    .string "I describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"
GiveTea::
    .string "Thanks for visiting, have this!\n"
    .string "OLD MAN gave {PLAYER} TEA$" 

CeruleanCity_House1_Text_AttackStatFlash::
    .string "The ATTACK stat of all your\n"
    .string "POKéMON increases a little bit.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "POKéMON up to Lv. 30 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "The SPEED stat of all your\n"
    .string "POKéMON increases a little bit.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "POKéMON up to Lv. 50 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "The DEFENSE stat of all your\n"
    .string "POKéMON increases a little bit.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "POKéMON up to Lv. 70 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "The SP. ATK and SP. DEF stats of\n"
    .string "all your POKéMON rise a little bit.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "All POKéMON will obey you!$"

